#pragma once

// Important! Character names may be subject of copyright
enum CharacterType {
	CHARACTER_TYPE_SOL,
	CHARACTER_TYPE_KY,
	CHARACTER_TYPE_MAY,
	CHARACTER_TYPE_MILLIA,
	CHARACTER_TYPE_ZATO,
	CHARACTER_TYPE_POTEMKIN,
	CHARACTER_TYPE_CHIPP,
	CHARACTER_TYPE_FAUST,
	CHARACTER_TYPE_AXL,
	CHARACTER_TYPE_VENOM,
	CHARACTER_TYPE_SLAYER,
	CHARACTER_TYPE_INO,
	CHARACTER_TYPE_BEDMAN,
	CHARACTER_TYPE_RAMLETHAL,
	CHARACTER_TYPE_SIN,
	CHARACTER_TYPE_ELPHELT,
	CHARACTER_TYPE_LEO,
	CHARACTER_TYPE_JOHNNY,
	CHARACTER_TYPE_JACKO,
	CHARACTER_TYPE_JAM,
	CHARACTER_TYPE_HAEHYUN,
	CHARACTER_TYPE_RAVEN,
	CHARACTER_TYPE_DIZZY,
	CHARACTER_TYPE_BAIKEN,
	CHARACTER_TYPE_ANSWER
};
