//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ggxrd_hitbox_overlay.rc
//
#define IDB_ACTIVE_FRAME                103
#define IDB_DIGIT_0                     104
#define IDB_DIGIT_1                     105
#define IDB_DIGIT_2                     106
#define IDB_DIGIT_3                     107
#define IDB_DIGIT_4                     108
#define IDB_DIGIT_5                     109
#define IDB_DIGIT_6                     110
#define IDB_DIGIT_7                     111
#define IDB_DIGIT_8                     112
#define IDB_DIGIT_9                     113
#define IDB_FIRST_FRAME                 114
#define IDB_LANDING_RECOVERY_FRAME      115
#define IDB_NON_ACTIVE_FRAME            116
#define IDB_PROJECTILE_FRAME            117
#define IDB_RECOVERY_FRAME              118
#define IDB_STARTUP_FRAME               119
#define IDB_STRIKE_INVUL                120
#define IDB_THROW_INVUL                 122
#define IDB_IDLE_FRAME                  124
#define IDB_XSTUN_FRAME                 125
#define IDB_ACTIVE_FRAME_NON_COLORBLIND 126
#define IDB_LANDING_RECOVERY_FRAME_NON_COLORBLIND 127
#define IDB_NON_ACTIVE_FRAME_NON_COLORBLIND 128
#define IDB_PROJECTILE_FRAME_NON_COLORBLIND 129
#define IDB_RECOVERY_FRAME_NON_COLORBLIND 130
#define IDB_STARTUP_FRAME_NON_COLORBLIND 131
#define IDB_XSTUN_FRAME_NON_COLORBLIND  132
#define IDR_MY_PIXEL_SHADER             135
#define IDB_IDLE_FRAME_CANT_BLOCK       137
#define IDB_IDLE_FRAME_CANT_FD          138
#define IDB_STARTUP_FRAME_CAN_BLOCK     139
#define IDB_STARTUP_FRAME_CAN_BLOCK_NON_COLORBLIND 140
#define IDB_SUPER_ARMOR_ACTIVE          141
#define IDB_SUPER_ARMOR_ACTIVE_NON_COLORBLIND 142
#define IDB_IDLE_FRAME_CANT_BLOCK_NON_COLORBLIND 143
#define IDB_IDLE_FRAME_CANT_FD_NON_COLORBLIND 144
#define IDB_IDLE_FRAME_ELPHELT_RIFLE    145
#define IDB_IDLE_FRAME_ELPHELT_RIFLE_NON_COLORBLIND 146
#define IDB_RECOVERY_FRAME_CAN_ACT      147
#define IDB_RECOVERY_FRAME_CAN_ACT_NON_COLORBLIND 148
#define IDB_RECOVERY_FRAME_HAS_GATLINGS 149
#define IDB_RECOVERY_FRAME_HAS_GATLINGS_NON_COLORBLIND 150
#define IDB_SUPER_ARMOR_ACTIVE_FULL     151
#define IDB_SUPER_ARMOR_ACTIVE_FULL_NON_COLORBLIND 152
#define IDB_IDLE_FRAME_ELPHELT_RIFLE_CAN_STOP_HOLDING 153
#define IDB_IDLE_FRAME_ELPHELT_RIFLE_CAN_STOP_HOLDING_NON_COLORBLIND 154
#define IDB_ACTIVE_FRAME_NEW_HIT        155
#define IDB_ACTIVE_FRAME_NEW_HIT_NON_COLORBLIND 156
#define IDB_ACTIVE_FRAME_HITSTOP        157
#define IDB_ACTIVE_FRAME_HITSTOP_NON_COLORBLIND 158
#define IDB_LANDING_RECOVERY_FRAME_CAN_CANCEL 159
#define IDB_LANDING_RECOVERY_FRAME_CAN_CANCEL_NON_COLORBLIND 160
#define IDB_ZATO_BREAK_THE_LAW_STAGE2   165
#define IDB_ZATO_BREAK_THE_LAW_STAGE2_NON_COLORBLIND 166
#define IDB_ZATO_BREAK_THE_LAW_STAGE3   167
#define IDB_ZATO_BREAK_THE_LAW_STAGE3_NON_COLORBLIND 168
#define IDB_ZATO_BREAK_THE_LAW_STAGE2_RELEASED 169
#define IDB_ZATO_BREAK_THE_LAW_STAGE2_RELEASED_NON_COLORBLIND 170
#define IDB_ZATO_BREAK_THE_LAW_STAGE3_RELEASED 171
#define IDB_ZATO_BREAK_THE_LAW_STAGE3_RELEASED_NON_COLORBLIND 172
#define IDB_GRAYBEAT_AIR_HITSTUN_NON_COLORBLIND 173
#define IDB_GRAYBEAT_AIR_HITSTUN        174
#define IDB_XSTUN_FRAME_HITSTOP         177
#define IDB_XSTUN_FRAME_HITSTOP_NON_COLORBLIND 178
#define IDB_XSTUN_FRAME_CAN_CANCEL      187
#define IDB_PNG2                        188
#define IDB_XSTUN_FRAME_CAN_CANCEL_NON_COLORBLIND 188

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        189
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
