#pragma once

enum TrainingSettingId {
	TRAINING_SETTING_DISPLAY_SETTINGS_ENEMY_STATUS /* TRP_DispDummy */,
    TRAINING_SETTING_DISPLAY_SETTINGS_DAMAGE_INFO /* TRP_DispDamage */,
    TRAINING_SETTING_DISPLAY_SETTINGS_INPUT_HITSTORY /* TRP_DispLog */,
    TRAINING_SETTING_DISPLAY_SETTINGS_VIRTUAL_STICK /* TRP_DispVirtualLever */,
    TRAINING_SETTING_DISPLAY_SETTINGS_VIRTUAL_STICKS_POSITION /* TRP_VirtualLeverPos */,
    TRAINING_SETTING_HP_REGEN /* TRP_HitPoint */,
    TRAINING_SETTING_PLAYER_1_MAX_HP /* TRP_HitPointMax1P */,
    TRAINING_SETTING_PLAYER_2_MAX_HP /* TRP_HitPointMax2P */,
    TRAINING_SETTING_TENSION_GAUGE /* TRP_TensionInitial */,
    TRAINING_SETTING_PSYCH_BURST /* TRP_BurstStock */,
    TRAINING_SETTING_RISC_LEVEL0 /* TRP_GuardBalance */,
    TRAINING_SETTING_COUNTER_HIT /* TRP_CounterHit */,
    TRAINING_SETTING_DANGER_TIME /* TRP_DangerTime */,
    TRAINING_SETTING_STUN /* TRP_Kizetsu */,
    TRAINING_SETTING_ENEMY_STATUS/* TRP_Enemy */,
    TRAINING_SETTING_COM_LEVEL /* TRP_CPULevel */,
    TRAINING_SETTING_SLOT_NUMBER /* TRP_MemorySlot */,
    TRAINING_SETTING_STANCE /* TRP_Posing */,
    TRAINING_SETTING_BLOCK_SETTINGS /* TRP_Guard */,
    TRAINING_SETTING_BLOCK_SWITCHING /* TRP_GuardSwitch */,
    TRAINING_SETTING_BLOCK_TYPE /* TRP_GuardType */,
    TRAINING_SETTING_RECOVERY /* TRP_AirUkemi */,
    TRAINING_SETTING_STAGGER_RECOVERY /* TRP_JitabataRecover */,
    TRAINING_SETTING_STUN_RECOVERY /* TRP_KizetsuRecover */,
    TRAINING_SETTING_AUTO_PSYCH_BURST /* TRP_AutoBurst */,
    TRAINING_SETTING_INPUT_LATENCY_1P /* TRP_Delay1P */,
    TRAINING_SETTING_INPUT_LATENCY_2P /* TRP_Delay2P */,
    TRAINING_SETTING_CHAR_SPECIFIC_SOL_DRAGON_INSTALL /* TRP_SOL */,
    TRAINING_SETTING_CHAR_SPECIFIC_MILLIA_SILENT_FORCE /* TRP_MLL */,
    TRAINING_SETTING_CHAR_SPECIFIC_ZATO_EDDIE_GAUGE /* TRP_ZAT */,
    TRAINING_SETTING_CHAR_SPECIFIC_CHIPP_SHURIKEN /* TRP_CHP */,
    TRAINING_SETTING_CHAR_SPECIFIC_FAUST_WHAT_COULD_THIS_BE /* TRP_FAU */,
    TRAINING_SETTING_CHAR_SPECIFIC_VENOM_BISHOP_RUNOUT /* TRP_VEN */,
    TRAINING_SETTING_CHAR_SPECIFIC_SIN_CALORIE_GAUGE /* TRP_SIN */,
    TRAINING_SETTING_CHAR_SPECIFIC_JOHNNY_GLITTER_IS_GOLD /* TRP_JHN0 */,
    TRAINING_SETTING_CHAR_SPECIFIC_JOHNNY_MIST_FINER /* TRP_JHN1 */,
    TRAINING_SETTING_CHAR_SPECIFIC_JACKO_P_GHOST /* TRP_JKO0 */,
    TRAINING_SETTING_CHAR_SPECIFIC_JACKO_K_GHOST /* TRP_JKO1 */,
    TRAINING_SETTING_CHAR_SPECIFIC_JACKO_S_GHOST /* TRP_JKO2 */,
    TRAINING_SETTING_CHAR_SPECIFIC_JACKO_SKILL_COOLDOWN /* TRP_JKO3 */,
    TRAINING_SETTING_CHAR_SPECIFIC_JAM_K_ASANAGI_NO_KOKYUU /* TRP_JAM0 */,
    TRAINING_SETTING_CHAR_SPECIFIC_JAM_S_ASANAGI_NO_KOKYUU /* TRP_JAM1 */,
    TRAINING_SETTING_CHAR_SPECIFIC_JAM_H_ASANAGI_NO_KOKYUU /* TRP_JAM2 */,
    TRAINING_SETTING_CHAR_SPECIFIC_RAVEN_EXCITEMENT /* TRP_RVN */,
    TRAINING_SETTING_DISPLAY_COMBO_RECIPE_RECORD /* TRP_DISP_ActRecord */,
    TRAINING_SETTING_DISPLAY_COMBO_RECIPE_RECIPE /* TRP_DISP_ActRecipe */
};

enum TrainingSettingValue_CounterHit {
	TRAINING_SETTING_VALUE_COUNTER_HIT_DEFAULT,
	TRAINING_SETTING_VALUE_COUNTER_HIT_FORCED,
	TRAINING_SETTING_VALUE_COUNTER_HIT_RANDOM,
	TRAINING_SETTING_VALUE_COUNTER_HIT_FORCED_MORTAL_COUNTER
};

using getTrainingSetting_t = int(__thiscall*)(void* trainingStruct, TrainingSettingId setting, BOOL outsideTraining);
